import { useState, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import AppHeader from "@/components/layout/AppHeader";
import VideoCapture from "@/components/report/VideoCapture";
import PhotoCapture, { GeoLocation } from "@/components/report/PhotoCapture";
import AIAnalysis from "@/components/report/AIAnalysis";
import { uploadToS3, submitReport } from "@/services/awsService";
import { toast } from "sonner";
import { ShieldAlert, FileText, MapPin } from "lucide-react";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";

const Report = () => {
  const navigate = useNavigate();
  const [description, setDescription] = useState("");
  const [wardArea, setWardArea] = useState("");

  const [videoCaptured, setVideoCaptured] = useState(false);
  const [photoCaptured, setPhotoCaptured] = useState(false);
  const [evidenceLocation, setEvidenceLocation] = useState<GeoLocation | null>(null);
  const [aiCategory, setAiCategory] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const isFormValid = description.trim().length >= 10 && wardArea.trim().length > 0;

  const handleVideoCapture = async (blob: Blob) => {
    setVideoCaptured(true);
    const key = `reports/video-${Date.now()}.webm`;
    const result = await uploadToS3(blob, key);
    if (result.success) {
      toast.success("Video evidence uploaded successfully");
    }
  };

  const handlePhotoCapture = async (blob: Blob, location: GeoLocation) => {
    setPhotoCaptured(true);
    setEvidenceLocation(location);
    const key = `reports/photo-${Date.now()}.jpg`;
    const result = await uploadToS3(blob, key);
    if (result.success) {
      toast.success("Geotagged photo uploaded successfully");
    }
  };

  const handleAIComplete = useCallback(async (category: string) => {
    setAiCategory(category);
    toast.info(`Auto-categorized as: ${category}`);

    if (!evidenceLocation) {
      toast.error("Location data is missing. Please retake photo.");
      return;
    }

    setIsSubmitting(true);
    const result = await submitReport({
      id: "", // ID generated by backend
      description,
      location: evidenceLocation,
      language: "en",
      timestamp: Date.now(),
      status: "pending",
      confirmations: 0
    });

    setIsSubmitting(false);

    if (result.success) {
      toast.success("Report successfully submitted to the server!");
      navigate("/", { replace: true });
    } else {
      toast.error("Failed to submit report. Please try again.");
    }

  }, [description, wardArea, evidenceLocation, navigate]);

  return (
    <div className="min-h-screen pb-24">
      <AppHeader title="Integrity Gatekeeper" />
      <main className="p-4 space-y-4">
        <div className="flex items-start gap-3 rounded-xl bg-warning/10 p-3">
          <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-warning" />
          <div>
            <p className="text-sm font-semibold text-foreground">Fraud Prevention Active</p>
            <p className="text-xs text-muted-foreground">
              A geotagged photo AND a 5-second live video are required to submit an issue.
            </p>
          </div>
        </div>

        <div className="glass-card rounded-xl p-4 space-y-4">
          <div className="space-y-2">
            <Label htmlFor="wardArea" className="flex items-center gap-1.5 font-bold">
              <MapPin className="h-4 w-4 text-primary" />
              Location / Ward Area
            </Label>
            <Input
              id="wardArea"
              placeholder="e.g. Sector 7, Viman Nagar"
              value={wardArea}
              onChange={(e) => setWardArea(e.target.value)}
              disabled={photoCaptured}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="description" className="flex items-center gap-1.5 font-bold">
              <FileText className="h-4 w-4 text-primary" />
              Issue Description
            </Label>
            <Textarea
              id="description"
              placeholder="Describe the problem in detail (minimum 10 characters)..."
              className="min-h-[100px] resize-none"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              disabled={photoCaptured}
            />
          </div>
        </div>

        {isFormValid ? (
          <div className="space-y-4">
            <PhotoCapture onCapture={handlePhotoCapture} />
            {photoCaptured && <VideoCapture onCapture={handleVideoCapture} />}
          </div>
        ) : (
          <p className="text-center text-sm text-muted-foreground pt-4">
            Please fill out the Location and Description to unlock evidence upload.
          </p>
        )}

        <AIAnalysis isActive={videoCaptured && photoCaptured && !isSubmitting} onComplete={handleAIComplete} />
      </main>
    </div>
  );
};

export default Report;
